name: first-github-action
on: push
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello github actions"
      - name: multiline script
        run: |
          node -v
          npm -v
  run-window-command:
    runs-on: windows-latest
    steps:
      - name: Directory powershell
        run: Get-Location